### ISSUE TITLE
Don't use raw messages from Nylas

### ISSUE THREAD

**Issue by AdriVanHoudt** [Salesflare/unimail#6]
Atm we use them all the time but they are only cached for 7 days.
If we can make it so we don't need the raw messages, it will give unimail a speed boost.
More info here https://docs.nylas.com/docs/how-nylas-works

**Comment by kdeclerck** [comment]
Fixed on messages.list calls in https://github.com/Salesflare/unimail/commit/fc4641890e8314c459997adda5a6862fe35e8181

On a messages.get call we still fetch the raw message since we want the detailed RFC 2822 headers in the response there.
